apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        resources:
          requests: { cpu: "150m", memory: "256Mi" }
          limits:   { cpu: "400m", memory: "512Mi" }
