apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "300m", memory: "256Mi" }
