apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits:   { cpu: "300m", memory: "512Mi" }
